### ISSUE TITLE
Sitemap doesn't rewrite URL's

### ISSUE THREAD

**Issue by GMTeams** [fritzmg/contao-simple-news-urls#10]
Contao 3.5.4
fritzmg/contao-simple-news-urls | 2.0.5

When I'm generating the searchindex, the URL's in the list are not rewritten, so the URL's in the sitemap are not rewritten too.

I think that is causing that my news sites are not indexed automatically by search engines, I always have to manually submit...

**Comment by fritzmg** [comment]
> I think that is causing that my news sites are not indexed automatically by search engines, I always have to manually submit...

That should not matter. The original URLs should still work.

**Comment by GMTeams** [comment]
Ok so you mean the (automatically) indexed URL would be the "original" version and when the user clicks the URL's are rewritten?

Then I have to figure out what is causing my problem with the index.
Thanks.

**Comment by fritzmg** [comment]
> Ok so you mean the (automatically) indexed URL would be the "original" version and when the user clicks the URL's are rewritten?

The original URL redirects to the short URL (depending on what you have configured in your `localconfig.php`).

**Comment by fritzmg** [comment]
Sitemap URLs are now rewritten too due to #13 ;)
