### ISSUE TITLE
Add possibility to respect folder urls

### ISSUE THREAD

**Issue by m-knorr** [fritzmg/contao-simple-news-urls#12]
It's awesome to remove the reader/detail/item whatever alias.

But could it be possible to respect the folder URLs before the detail?

F.E.:

www.example.com/blog/category/detail/mynewsentry.html

currently this will be stripped to www.example.com/newsentry.html

but is possible to rewrite to www.example.com/blog/category/mynewsentry.html

This would be a great enhancement in case of clear URL structures for SEO etc.

**Comment by fritzmg** [comment]
> currently this will be stripped to www.example.com/newsentry.html

That is the purpose of the extension.

> but is possible to rewrite to www.example.com/blog/category/mynewsentry.html

That's not the purpose of this extension. What you want is something can be done with the [urlcleaner](https://contao.org/en/extension-list/view/urlcleaner.de.html) extension.
