### ISSUE TITLE
search indexing not possible

### ISSUE THREAD

**Issue by reluem** [fritzmg/contao-simple-news-urls#13]
with the simple news extension in contao 4.5.10, the search indexing is apparently not working.
the search buildup is confused by the 302 status code.

I don't understand why the system recognizes it as a 302, since per default it should be a 301, right?
Weirdly, the http://301re.direct/ recognizes it as a 301.

<img width="252" alt="bildschirmfoto 2018-08-07 um 22 05 45" src="https://user-images.githubusercontent.com/17430489/43799520-0f1d230c-9a8e-11e8-950d-ef82d709c918.png">

**Comment by fritzmg** [comment]
Fixed in `3.0.1`.

**Comment by fritzmg** [comment]
> I don't understand why the system recognizes it as a 302, since per default it should be a 301, right?

This seems to happen automatically when it's an AJAX request - not sure if that is done on purpose by Contao.

**Comment by reluem** [comment]
Thank you! 
Seems to be working now
