### ISSUE TITLE
Compatibility with Contao 4.7

### ISSUE THREAD

**Issue by reluem** [fritzmg/contao-simple-news-urls#14]
Hi, 

I just wanted to let you know that this package does not work as expected any longer in the new contao 4.7.
News URLs still work fine (www.domain.com/news-123), the matching of the homepage on the other hand is broken (www.domain.com does not resolve to articles with 'index' or '/'). 

If I remove this package, the routing works fine again.

> [2019-02-16 10:24:30] app.DEBUG: Router Symfony\Cmf\Component\Routing\DynamicRouter was not able to match, message "Page alias is empty" [] []
> [2019-02-16 10:24:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /Users/xyz/xyz/xyz/vendor/symfony/http-kernel/EventListener/RouterListener.php line 139
> 
> Symfony\Component\Routing\Exception\ResourceNotFoundException:
> None of the routers in the chain matched this request
> GET /app_dev.php HTTP/2.0
> Accept:          text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Encoding: br, gzip, deflate
> Accept-Language: de-at
> Host:           xyz.dev

**Comment by fritzmg** [comment]
I'll have a look at the issue. I am guessing this also affects [fritzmg/contao-short-urls](https://github.com/fritzmg/contao-short-urls).

**Comment by reluem** [comment]
Thanks!
With the new CMF Router, I most probably don't need extension anymore once the reader page can be [eliminated](https://github.com/contao/contao/issues/220#issuecomment-449033203).

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/pull/343
