### ISSUE TITLE
Preview broken on news reader pages with suffix manipulation

### ISSUE THREAD

**Issue by johannes-bittner** [fritzmg/contao-simple-news-urls#15]
Getestet in einer frischen 4.9.5: Beim Zusammenspiel mit fehlenden Suffixen gibt es Probleme mit der Preview-Funktion auf Newsreader-Seiten. Wenn ich /app/config/config.yml anlege mit dem Inhalt:

```
contao: 
   url_suffix: ''

```
... dann funktioniert auf einer News-Reader-Seite die Preview-Funktion nicht mehr, sondern es wird eine Weiterleitungswarnung ausgegeben (Diese Seite funktioniert nicht ... hat Sie zu oft weitergeleitet. Löschen Sie Ihre Cookies. ERR_TOO_MANY_REDIRECTS)

Der normale Aufruf ohne Preview klappt.

**Comment by fritzmg** [comment]
Fixed in 63ac174fef097bb64624c81c6c0fadf2ba8aced1 and released in `3.0.3` 👍

**Comment by johannes-bittner** [comment]
Getestet in zwei 4.9.7, mit oder ohne Suffix-Anpassung in /app/config/config.yml: Preview der Reader-Seite funktioniert, ohne Preview landet man in einem Redirect-Loop. Mit einem Downgrade auf 3.0.1 klappt es in der regulären Ansicht, aber in der Preview kommt der Redirect-Loop.

**Comment by fritzmg** [comment]
Yeah I think I know what the problem is. Can you please test the current `dev-master` version (bec6531)?

**Comment by johannes-bittner** [comment]
dev-master does the trick ... 👏👌🏆🏅🎖

**Comment by fritzmg** [comment]
Released in `3.0.4` :)
