### ISSUE TITLE
Apply this to Events?

### ISSUE THREAD

**Issue by spirescreative** [fritzmg/contao-simple-news-urls#16]
Any way to apply this same simple URL rewrite to events? 
Currently, the event reader is in the event URL same as the news reader was in news URL.
events/event-reader/new-event.html to events/new-event.html

**Comment by fritzmg** [comment]
You can already do what you want without this extension by selecting a news or event reader module in the news or event list module. Additionally the news archive or calendar's redirect page must point to the page containing the list module.

See also https://docs.contao.org/manual/en/core-extensions/calendar/frontend-modules/#module-configuration-2

**Comment by spirescreative** [comment]
Ah! Perfect. My list / reader setup was based on the Contao demo site which uses a redirect to a separate page for the reader module. Your suggestion works well. Thank you.
