### ISSUE TITLE
URL rewrite for List Module Records

### ISSUE THREAD

**Issue by spirescreative** [fritzmg/contao-simple-news-urls#17]
I put the following question out to the Contao community with regards to Clean URLs for the List Reader:
https://community.contao.org/en/showthread.php?24906-Clean-URLs-for-List-Reader

The initial response was to utilize the contao-simple-news-urls methods. It seems to be an approach which has potential, but I'm unsure of how this would be implemented.

Any insight would be helpful. Thank you!

**Comment by fritzmg** [comment]
You install this extension and that's it ;). There is no configuration.

**Comment by fritzmg** [comment]
Since version 4 this feature can (needs to be) enabled per news archive, jfyi.
