### ISSUE TITLE
Umlaute in alias breaks routing -> 404

### ISSUE THREAD

**Issue by Metis77** [fritzmg/contao-simple-news-urls#19]
If there are any german Umlaute in the url, the 404 page is delivered.

After replacing the Umlaute like ä -> ae in the news aliases it works perfectly.

**Comment by fritzmg** [comment]
I have looked at the issue but unfortunately cannot figure out how to fix routing for encoded URLs. I tried to fix it in https://github.com/fritzmg/contao-simple-news-urls/commit/ca9d1721e2a2482ea136f169e6d2a6213c3ce19b (you can test that in `dev-master`), but that did not fix it either (even though I thought it should).

I would need help from someone who as more insight with Symfony routing.

**Comment by fritzmg** [comment]
nvm, the fix was very simple. Released in `4.0.1` :)

**Comment by Metis77** [comment]
runs like a charm, thank you!
