### ISSUE TITLE
long loading news article

### ISSUE THREAD

**Issue by DVeris** [fritzmg/contao-simple-news-urls#5]
when you press on the link (by news article) - site thinks for a long time
## 

sorry for my english

**Comment by DVeris** [comment]
do you testing this module on real site?

**Comment by fritzmg** [comment]
Can you provide a link?

**Comment by fritzmg** [comment]
Yes, this module is active on "real sites".

**Comment by DVeris** [comment]
url

**Comment by DVeris** [comment]
we have over 3000 news article

**Comment by DVeris** [comment]
we have 20-30 pages

**Comment by DVeris** [comment]
this loading fast
url
this not
url

**Comment by DVeris** [comment]
and this loading fast
url   (news archive page)

**Comment by fritzmg** [comment]
Yeah, it's only this news article, that has a long respone time: …

If you disable the extension, how long is the response time for that news article? I doubt it has anything to do with this extension.

**Comment by DVeris** [comment]
module disables
please testing

**Comment by DVeris** [comment]
*module is disabled

**Comment by DVeris** [comment]
url

**Comment by DVeris** [comment]
now loaded fast

**Comment by DVeris** [comment]
maybe conflict with other module? for example?

**Comment by fritzmg** [comment]
Hm, no idea. Which Contao version are you using?

In total there are 3 database queries when using the Short URL:
- one to check if the URL is a valid news alias
- one to load the news archive of the news entry
- one to load the redirect page of the news archive

But these should all be pretty fast.

**Comment by DVeris** [comment]
news_pagination
tags
tags_news

**Comment by DVeris** [comment]
contao 3

**Comment by fritzmg** [comment]
Well, enable simple_news_urls again and disable tags, tags_news and news_pagination to see whether it has any effect.

**Comment by DVeris** [comment]
wow

**Comment by DVeris** [comment]
newspagination!

**Comment by DVeris** [comment]
now fast

**Comment by DVeris** [comment]
thank you for VERY necessary module

**Comment by DVeris** [comment]
how donate?

**Comment by DVeris** [comment]
))

**Comment by fritzmg** [comment]
Hm, ok :). But I don't know why news_pagination would cause this, I'd have to investigate that.

Regarding donations: on the Contao forum we donate each other with Amazon wishlists: http://www.amazon.de/wishlist/3TM66BLIY8328 (but currently I only have rather expensive items in there)

**Comment by DVeris** [comment]
please delete my site url in your post here 

paypal?

**Comment by fritzmg** [comment]
May PayPal account is email@spikx.net
