### ISSUE TITLE
canonical url and url in rss and search indexer

### ISSUE THREAD

**Issue by DVeris** [fritzmg/contao-simple-news-urls#6]
maybe add canonical url? (in newsreader)
$GLOBALS['TL_HEAD'][] = '<link rel="canonical" href="...

feeds use old urls
and maybe search indexer

**Comment by fritzmg** [comment]
The canonical tag is not needed (in theory), because the _simple_news_urls_ extension replaces the default Contao Newsreader and creates a 301 Redirect to the short URL. The search indexer should already build the short URLs, unless it does not use Contao's `generateFrontendUrl` function.

**Comment by DVeris** [comment]
301 ? old url works fine
post data?

**Comment by DVeris** [comment]
old url must works

**Comment by fritzmg** [comment]
There is a redirect here: https://github.com/fritzmg/contao-simple-news-urls/blob/master/system/modules/simple_news_urls/modules/ModuleNewsReaderRedirect.php#L38
This class replaces the default Newsreader: https://github.com/fritzmg/contao-simple-news-urls/blob/master/system/modules/simple_news_urls/config/config.php#L21

However, it could be, that other extensions also replace the default news reader and thus it might not work. May be I'll implement this another way then.

**Comment by DVeris** [comment]
you about newspagination?
or about old urls ?

**Comment by fritzmg** [comment]
Does #7 also fix your problem here?

**Comment by DVeris** [comment]
yes
super! thank you for speed :)

**Comment by fritzmg** [comment]
No problem ;)
