### ISSUE TITLE
enclosures are not working

### ISSUE THREAD

**Issue by DVeris** [fritzmg/contao-simple-news-urls#8]
301 redirect 

$enclosure['href']
page simple updating

not downloads files

**Comment by fritzmg** [comment]
I cannot reproduce the problem. When I access a news entry e.g. via

```
example.org/news/entry/news-with-enclosures.html
```

I am redirected to

```
example.org/news-with-enclosures.html
```

and there I can download the enclosures just fine.

**Comment by fritzmg** [comment]
@DVeris can you please try version `2.0.4` and see if that fixes your issue?

**Comment by DVeris** [comment]
Sorry for the long time answer!

simple_news_urls    1.1.2 - enclosures are not working in news
simple_news_urls    2.0.4 - all ok!

**Comment by fritzmg** [comment]
Good :)
