### ISSUE TITLE
when alias not unique...

### ISSUE THREAD

**Issue by DVeris** [fritzmg/contao-simple-news-urls#9]
when moving from multiple sites to one (contao)
i received news with the same aliases
((

simple news urls 
display only first news
other - 404

for example:
site1.com/newsalias.html (id 1) - works
site2.com/newsalias.html (id 2) - 404

whether it is possible to make something?

ps news have different news archives

**Comment by DVeris** [comment]
when disable simple news urls and setting the reader module (from all news archive) - news are works

site1.com/hot/newsalias.html
site2.com/hot/newsalias.html

**Comment by fritzmg** [comment]
How did you end up with duplicate aliases? Contao does not allow that for news.

I don't think what you want will really be possible - because there is no way of knowing for sure that one news is only valid for on particular domain. Sure, the redirect target of the parent news archive only points to one domain - however there can be newsreader modules that allow to display the news of both domains.

You should rename the alias of one of those news and then create a permanent redirect for one particular domain.

**Comment by DVeris** [comment]
i found problem
// check if target page is in the right domain
					if( $objTarget->domain && stripos( \Environment::get('host'), $objTarget->domain ) === false )
					{
						// return fragments without change
						return $arrFragments;
					}

**Comment by DVeris** [comment]
\Environment::get('host') = site1.com
$objTarget->domain = site2.com

**Comment by DVeris** [comment]
will there be consequences after deleting this code?

**Comment by DVeris** [comment]
ps I have moved 10 wordpress of the websites into 1 contao (sql) therefore it has so turned out

**Comment by DVeris** [comment]
sorry for my english)) translated ))

**Comment by fritzmg** [comment]
> will there be consequences after deleting this code?

If you remove this line then in theory `site1.com/newsalias.html` won't work anymore.

Why are you not renaming the alias?

**Comment by DVeris** [comment]
all urls are work! 

> Why are you not renaming the alias?

there are a lot of them
impossibly

**Comment by DVeris** [comment]
over 100.000 news
10-20% duplicate aliases (and maybe more)

**Comment by fritzmg** [comment]
> all urls are work!

But that is not possible. [This line](https://github.com/fritzmg/contao-simple-news-urls/blob/2.0.5/system/modules/simple_news_urls/classes/SimpleNewsUrls.php#L46) will only find exactly one news entry. If you have multiple news entries with the same alias, just one of those will be returned. Which will mean that this extension (or rather the newsreader later on) will show you only that news and never one of the other news with the same alias.

**Comment by DVeris** [comment]
these news identical
for example 10 identical news with duplicate aliases
this news for different sites

site1.com - news_archive1
site2.com - news_archive2
...

task was that the links were workers
site1.com/mynews-about-car
site2.com/mynews-about-car
...

**Comment by DVeris** [comment]
hmmm... testing
>But that is not possible.

it turns out that it is possible

site1.com/mynews-about-car
site2.com/mynews-about-car

have different text

**Comment by DVeris** [comment]
super))

**Comment by fritzmg** [comment]
> it turns out that it is possible
> 
> site1.com/mynews-about-car
> site2.com/mynews-about-car

I think that only happens to work in your case, because the redirect page has the same alias in each domain.
